"""Generation layer.

Character choices are generated by the DAL-grounded choice grammar in ``app.generation.choices``
(``parse_request`` -> ``generate_choices``); the derivation pipeline (``app.derivation.document``)
turns those choices into the five-schema document. The backstory (flavour) generator remains a
separate model call.

  - choices    character choices, grammar-constrained (see ``app.generation.choices``)
  - backstory  flavour bundle (physical + personality + backstory)

Shared: client.py (model I/O), helpers.py (flavour/name compute)."""
from app.generation.backstory import generate as generate_backstory  # noqa: F401  (re-exported)
