"""Generation layer.

Character choices are generated by the DAL-grounded choice grammar in the model-free rule engine
(``engine.choices``, ``parse_request``); the generator's own two-pass model-call seam
(``app.generation.choices.generate_choices``) drives the model against that grammar, and the engine's
derivation pipeline (``engine.derivation.document``) turns the resulting choices into the five-schema
document. The backstory (flavour) generator remains a separate model call.

  - choices    the model-call seam over the engine grammar (see ``app.generation.choices``)
  - backstory  flavour bundle (physical + personality + backstory)

Shared: client.py (model I/O), helpers.py (flavour/name compute)."""
from app.generation.backstory import generate as generate_backstory  # noqa: F401  (re-exported)
